repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        files: ^(.*\.py|(src|tests|docs)/(.*/)*.*\.py)$
-   repo: https://github.com/timothycrosley/isort
    rev: 5.5.2
    hooks:
    -   id: isort
        files: ^(.*\.py|(src|tests|docs)/(.*/)*.*\.py)$
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 5.1.1
    hooks:
    -   id: pydocstyle
        files: ^(src|tests)/(.*/)*.*\.py$
