repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-symlinks
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-toml
        exclude: tmpl/
    -   id: check-yaml
        exclude: tmpl/
#-   repo: https://github.com/myint/rstcheck
#    rev: v6.1.0
#    hooks:
#    -   id: rstcheck
#        additional_dependencies:
#        -   sphinx==5.0.1
#        -   sphinx-mdinclude
#        exclude: tmpl/
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
    -   id: codespell
