repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/myint/rstcheck
    rev: ''
    hooks:
    -   id: rstcheck
        additional_dependencies:
        -   sphinx==2.4.4
-   repo: https://github.com/codespell-project/codespell
    rev: v1.17.1
    hooks:
    -   id: codespell
