name: mch-python-blueprint
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - babel=2.11.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfgv=3.3.1
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - cryptography=39.0.0
  - distlib=0.3.6
  - docutils=0.19
  - filelock=3.9.0
  - identify=2.5.12
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=6.0.0
  - jinja2=3.1.2
  - ld_impl_linux-64=2.39
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - markupsafe=2.1.1
  - ncurses=6.3
  - nodeenv=1.7.0
  - openssl=3.0.7
  - packaging=22.0
  - pip=22.3.1
  - platformdirs=2.6.2
  - pre-commit=2.21.0
  - pycparser=2.21
  - pygments=2.14.0
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.11.0
  - python_abi=3.11
  - pytz=2022.7
  - pyyaml=6.0
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=65.6.3
  - snowballstemmer=2.2.0
  - sphinx=6.0.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - tk=8.6.12
  - toml=0.10.2
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ukkonen=1.0.1
  - urllib3=1.26.13
  - virtualenv=20.17.1
  - wheel=0.38.4
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.11.0
  - pip:
    - copier==7.0.1
    - dunamai==1.15.0
    - iteration-utilities==0.11.0
    - jinja2-ansible-filters==1.3.2
    - mistune==2.0.4
    - pathspec==0.10.3
    - plumbum==1.8.1
    - prompt-toolkit==3.0.36
    - pydantic==1.10.4
    - pyyaml-include==1.3
    - questionary==1.10.0
    - sphinx-mdinclude==0.5.3
    - wcwidth==0.2.5
