name: mch-python-blueprint
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  # runtime
  - pip:
    - copier>=6.1
  # development
  - pre-commit>=2.20
  - sphinx
  - pip
  - pip:
    - sphinx-mdinclude
