name: Formatting & compliance

on:
  push:
    branches:
    - actions
  pull_request:
    branches:
    - actions

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.7
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge
        channel-priority: flexible
        show-channel-urls: true
    - name: Install dependencies
      run: |
        conda create -n blueprint
        conda activate blueprint
        conda install --yes --file requirements/requirements.in
        conda deactivate
    - name: Install dev dependencies
      run: |
        conda create -n dev_blueprint
        conda activate dev_blueprint
        conda install --yes --file requirements/dev-requirements.in
        conda deactivate

    - name: pre-commit install-hooks
      run: |
        conda activate dev_blueprint
        pre-commit install-hooks
    - name: pre-commit run checks
      run: |
        conda activate dev_blueprint
        pre-commit run --all-files
