pipeline {
    environment {
       PATH = "$WORKSPACE/miniconda/bin:$PATH"
    }
    agent {
        label 'tsa'
    }

    post {
        always{
            echo 'Cleaning up workspace'
            deleteDir()
        }
    }
    stages {
        stage('setup miniconda') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                bash install.sh -p ${WORKSPACE}
                '''
            }
        }
        stage('build package') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                cd ${WORKSPACE}
                $CONDA_PREFIX/bin/python installer.py --name {{ cookiecutter.project_slug }}
                '''
            }
        }
        stage('test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate {{ cookiecutter.project_slug }}
                python -m pip install -U pip
                python -m pip install .
                pytest tests
                '''
            }
        }
        stage('dev-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate
                cd ${WORKSPACE}
                ${CONDA_PREFIX}/bin/python installer.py --name flying_circus --dev
                '''
            }
        }
        stage('dev-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate dev-{{ cookiecutter.project_slug }}
                pytest tests
                '''
            }
        }
        stage('pinned-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda create --yes -n pinned-{{ cookiecutter.project_slug }}
                conda activate {{ cookiecutter.project_slug }}
                conda install --yes --file requirements/requirements.txt
                '''
            }
        }
        stage('pinned-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate pinned-{{ cookiecutter.project_slug }}
                python -m pip install -U pip
                python -m pip install .
                pytest tests
                '''
            }
        }
        stage('pinned-dev-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda create --yes -n pinned-dev-{{ cookiecutter.project_slug }}
                conda activate {{ cookiecutter.project_slug }}
                conda install --yes --file requirements/requirements.txt
                conda install --yes --file requirements/dev-requirements.txt
                '''
            }
        }
        stage('pinned-dev-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate pinned-dev-{{ cookiecutter.project_slug }}
                python -m pip install -U pip
                python -m pip install .
                pytest tests
                '''
            }
        }
    }
}