pipeline {
    environment {
       PATH = "$WORKSPACE/miniconda/bin:$PATH"
    }
    agent {
        label 'tsa'
    }

    post {
        always{
            echo 'Cleaning up workspace'
            deleteDir()
        }
    }
    stages {
        stage('setup miniconda') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                bash setup_miniconda.sh -p ${WORKSPACE}
                '''
            }
        }
        stage('build package') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                cd ${WORKSPACE}/{{cookiecutter.project_slug}}
                source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                bash installer.sh -n {{cookiecutter.project_slug}}
                '''
            }
        }
        stage('test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate {{ cookiecutter.project_slug }}
                cd ${WORKSPACE}/{{cookiecutter.project_slug}}
                pytest tests
                '''
            }
        }
        stage('dev-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/{{cookiecutter.project_slug}}
                bash installer.sh -n dev-{{cookiecutter.project_slug}} -d -c
                '''
            }
        }
        stage('dev-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate dev-{{cookiecutter.project_slug}}
                cd ${WORKSPACE}/{{cookiecutter.project_slug}}
                pytest tests
                '''
            }
        }
        stage('pinned-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/{{cookiecutter.project_slug}}
                bash installer.sh -n pinned-{{cookiecutter.project_slug}} -p -c
                '''
            }
        }
        stage('pinned-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate pinned-{{cookiecutter.project_slug}}
                cd ${WORKSPACE}/{{cookiecutter.project_slug}}
                pytest tests
                '''
            }
        }
        stage('pinned-dev-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/{{cookiecutter.project_slug}}
                bash installer.sh -n pinned-dev-{{cookiecutter.project_slug}} -p -d -c
                '''
            }
        }
        stage('pinned-dev-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate pinned-dev-{{cookiecutter.project_slug}}
                cd ${WORKSPACE}/{{cookiecutter.project_slug}}
                pytest tests
                '''
            }
        }
    }
}
