name: Run pre-commit in blueprint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  blueprint-pre-commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.7
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge
        channel-priority: flexible
        show-channel-urls: true
    - name: Create dev env from unpinned reqs
      run: |
        conda env create --name dev_env --file requirements/requirements.yml
        conda env update --name dev_env --file requirements/dev-requirements.yml
        conda run --name dev_env pip install --no-deps .
    - name: Install pre-commit hooks
      run: |
        conda run --name dev_env pre-commit install-hooks
    - name: Run pre-commit hooks
      run: |
        conda run --name dev_env pre-commit run --all-files
