pipeline {
    environment {
       PATH = "$WORKSPACE/miniconda/bin:$PATH"
    }
    agent {
        label 'tsa'
    }

    post {
        always{
            echo 'Cleaning up workspace'
            deleteDir()
        }
    }
    stages {
        stage('setup miniconda') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                cp {{cookiecutter.project_slug}}/setup_miniconda.sh .
                bash setup_miniconda.sh -p ${WORKSPACE}
                '''
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda create -n cookiecutter
                conda activate cookiecutter
                conda install -c conda-forge cookiecutter
                cookiecutter --no-input .
                conda deactivate
                '''
            }
        }
        stage('build package') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                cd ${WORKSPACE}/flying_circus
                source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                bash setup_env.sh -n flying_circus -u
                conda activate flying_circus
                pip install .
                '''
            }
        }
        stage('test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate flying_circus
                cd ${WORKSPACE}/flying_circus
                pytest tests
                '''
            }
        }
        stage('dev-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/flying_circus
                bash setup_env.sh -n flying_circus -d -u
                conda activate flying_circus-dev
                pip install --editable .
                '''
            }
        }
        stage('dev-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate flying_circus-dev
                cd ${WORKSPACE}/flying_circus
                pytest tests
                '''
            }
        }
        stage('pinned-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/flying_circus
                bash setup_env.sh -n pinned-flying_circus
                conda activate pinned-flying_circus
                pip install .
                '''
            }
        }
        stage('pinned-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate pinned-flying_circus
                cd ${WORKSPACE}/flying_circus
                pytest tests
                '''
            }
        }
        stage('pinned-dev-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/flying_circus
                bash setup_env.sh -n pinned-flying_circus -d
                conda activate pinned-flying_circus-dev
                pip install --editable .
                '''
            }
        }
        stage('pinned-dev-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate pinned-flying_circus-dev
                cd ${WORKSPACE}/flying_circus
                pytest tests
                '''
            }
        }
    }
}
