name: mch-python-blueprint
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.13
  - babel=2.14.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - certifi=2023.11.17
  - cffi=1.16.0
  - cfgv=3.3.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - distlib=0.3.8
  - filelock=3.13.1
  - identify=2.5.33
  - idna=3.6
  - imagesize=1.4.1
  - importlib-metadata=7.0.0
  - jinja2=3.1.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.44.2
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - markupsafe=2.1.3
  - ncurses=6.4
  - nodeenv=1.8.0
  - openssl=3.2.0
  - packaging=23.2
  - pip=23.3.2
  - platformdirs=4.1.0
  - pre-commit=3.6.0
  - pycparser=2.21
  - pygments=2.17.2
  - pysocks=1.7.1
  - python=3.10.13
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - snowballstemmer=2.2.0
  - sphinx=7.2.6
  - sphinxcontrib-applehelp=1.0.7
  - sphinxcontrib-devhelp=1.0.5
  - sphinxcontrib-htmlhelp=2.0.4
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.6
  - sphinxcontrib-serializinghtml=1.1.9
  - tk=8.6.13
  - tzdata=2023c
  - ukkonen=1.0.1
  - urllib3=2.1.0
  - virtualenv=20.25.0
  - wheel=0.42.0
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.17.0
  - pip:
      - copier==7.2.0
      - docutils==0.19
      - dunamai==1.19.0
      - funcy==2.0
      - jinja2-ansible-filters==1.3.2
      - mistune==2.0.5
      - pathspec==0.12.1
      - plumbum==1.8.2
      - prompt-toolkit==3.0.36
      - pydantic==1.10.13
      - pyyaml-include==1.3.1
      - questionary==2.0.1
      - rstcheck-core==1.0.3
      - sphinx-mdinclude==0.5.3
      - types-docutils==0.19.1.9
      - typing-extensions==4.9.0
      - wcwidth==0.2.12
