name: mch-python-blueprint
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.13
  - babel=2.13.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.16.0
  - cfgv=3.3.1
  - charset-normalizer=3.3.1
  - colorama=0.4.6
  - distlib=0.3.7
  - docutils=0.20.1
  - filelock=3.12.4
  - identify=2.5.30
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=6.8.0
  - jinja2=3.1.2
  - ld_impl_linux-64=2.40
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.43.2
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - markupsafe=2.1.3
  - ncurses=6.4
  - nodeenv=1.8.0
  - openssl=3.1.3
  - packaging=23.2
  - pip=23.3.1
  - platformdirs=3.11.0
  - pre-commit=3.5.0
  - pycparser=2.21
  - pygments=2.16.1
  - pysocks=1.7.1
  - python=3.12.0
  - python_abi=3.12
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - snowballstemmer=2.2.0
  - sphinx=7.2.6
  - sphinxcontrib-applehelp=1.0.7
  - sphinxcontrib-devhelp=1.0.5
  - sphinxcontrib-htmlhelp=2.0.4
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.6
  - sphinxcontrib-serializinghtml=1.1.9
  - tk=8.6.13
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - ukkonen=1.0.1
  - urllib3=2.0.7
  - virtualenv=20.24.4
  - wheel=0.41.2
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.17.0
  - pip:
      - annotated-types==0.6.0
      - copier==7.2.0
      - dunamai==1.19.0
      - funcy==2.0
      - jinja2-ansible-filters==1.3.2
      - mistune==2.0.5
      - pathspec==0.11.2
      - plumbum==1.8.2
      - prompt-toolkit==3.0.36
      - pydantic==1.10.13
      - pydantic-core==2.10.1
      - pyyaml-include==1.3.1
      - questionary==2.0.1
      - sphinx-mdinclude==0.5.3
      - wcwidth==0.2.8
