name: mch-python-blueprint
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip>=22.3
  # development
  - pre-commit>=2.20
  - sphinx>=4.3
  - pip:
    # runtime
    - copier>=8.1
    # development
    - sphinx-mdinclude>=0.5
