channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - astroid=2.13.2
  - asttokens=2.2.1
  - attrs=22.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=22.10.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfgv=3.3.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - codespell=2.2.2
  - colorama=0.4.6
  - cryptography=39.0.0
  - decorator=5.1.1
  - dill=0.3.6
  - distlib=0.3.6
  - docutils=0.17.1
  - exceptiongroup=1.1.0
  - executing=1.2.0
  - filelock=3.9.0
  - flake8=6.0.0
  - flake8-black=0.3.5
  - identify=2.5.13
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=3.3.0
  - iniconfig=2.0.0
  - ipdb=0.13.11
  - ipython=8.8.0
  - isort=5.11.4
  - jedi=0.18.2
  - jinja2=3.1.2
  - lazy-object-proxy=1.9.0
  - ld_impl_linux-64=2.39
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - livereload=2.6.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mypy=0.991
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - nodeenv=1.7.0
  - openssl=3.0.7
  - packaging=23.0
  - parso=0.8.3
  - pathspec=0.10.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - platformdirs=2.6.2
  - pluggy=1.0.0
  - pre-commit=2.21.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pydantic=1.10.4
  - pydocstyle=6.2.2
  - pyflakes=3.0.1
  - pygments=2.14.0
  - pylint=2.15.10
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - pytest=7.2.0
  - python=3.11.0
  - python_abi=3.11
  - pytoolconfig=1.2.4
  - pytz=2022.7
  - pyyaml=6.0
  - readline=8.1.2
  - requests=2.28.1
  - rope=1.6.0
  - rstcheck=6.1.1
  - rstcheck-core=1.0.2
  - setuptools=65.6.3
  - shellingham=1.5.0.post1
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sphinx=4.3.2
  - sphinx-autobuild=2021.3.14
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - stack_data=0.6.2
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.6
  - tornado=6.2
  - traitlets=5.8.1
  - typer=0.4.2
  - types-docutils=0.18.3
  - typing=3.10.0.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ukkonen=1.0.1
  - urllib3=1.26.14
  - virtualenv=20.17.1
  - wcwidth=0.2.5
  - wheel=0.38.4
  - wrapt=1.14.1
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.11.0
  - pip:
      - flake8-pyproject==1.2.2
      - mistune==2.0.4
      - sphinx-mdinclude==0.5.3
