channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=22.2.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - click=8.1.3
  - colorama=0.4.6
  - exceptiongroup=1.1.0
  - iniconfig=2.0.0
  - ld_impl_linux-64=2.39
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.7
  - packaging=23.0
  - pip=22.3.1
  - pluggy=1.0.0
  - pytest=7.2.0
  - python=3.11.0
  - readline=8.1.2
  - setuptools=65.6.3
  - tk=8.6.12
  - tomli=2.0.1
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.6
