name: Pre-commit and pytest in new project

on:
  push:
    branches:
    - dev_refactor
  pull_request:
    branches:
    - dev_refactor

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.7
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge
        channel-priority: flexible
        show-channel-urls: true
    - name: Create new project
      run: |
        conda env create --name blueprint --file requirements/requirements.yml
        mkdir test
        cd test
        conda run --name blueprint cookiecutter --replay ..
    - name: Create dev env from unpinned reqs
      run: |
        cd test/flying_circus
        conda env create --name flying-circus-dev --file requirements/requirements.yml
        conda env update --name flying-circus-dev --file requirements/dev-requirements.yml
    - name: Run pre-commit hooks
      run: |
        cd test/flying_circus
        conda run --name flying-circus-dev pre-commit install-hooks
        conda run --name flying-circus-dev pre-commit run --all-files
    - name: Run unit tests
      run: |
        cd test/flying_circus
        conda run --name flying-circus-dev pytest
